#############################################################################
# Makefile for building: vegaihm
# Generated by qmake (2.01a) (Qt 4.4.3) on: jeu. nov. 5 21:47:39 2009
# Project:  vegaihm.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile vegaihm.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT3_SUPPORT -DQT3_SUPPORT -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtSql -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Irude -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = -lQtSql -lQtNetwork ./librudeconfig.a -lQtSql -lQtNetwork ./librudeconfig.a $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = configuration.cpp \
		controlLink.cpp \
		debug.cpp \
		DeviceKeysConfig.cpp \
		liveEvents.cpp \
		main.cpp \
		md5.c \
		parameters.cpp \
		printer.cpp \
		switch.cpp \
		vega_ihm.cpp \
		vega_ui_authentication.cpp \
		vega_ui_conferences.cpp \
		vega_ui_controllink.cpp \
		vega_ui_devices.cpp \
		vega_ui_groups.cpp \
		vega_ui_init.cpp \
		vega_ui_liveevents.cpp \
		vega_ui_searchdb.cpp \
		vega_ui_system_status.cpp moc_liveEvents.cpp \
		moc_parameters.cpp \
		moc_vega_ihm.cpp \
		qrc_icons.cpp
OBJECTS       = configuration.o \
		controlLink.o \
		debug.o \
		DeviceKeysConfig.o \
		liveEvents.o \
		main.o \
		md5.o \
		parameters.o \
		printer.o \
		switch.o \
		vega_ihm.o \
		vega_ui_authentication.o \
		vega_ui_conferences.o \
		vega_ui_controllink.o \
		vega_ui_devices.o \
		vega_ui_groups.o \
		vega_ui_init.o \
		vega_ui_liveevents.o \
		vega_ui_searchdb.o \
		vega_ui_system_status.o \
		moc_liveEvents.o \
		moc_parameters.o \
		moc_vega_ihm.o \
		qrc_icons.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		vegaihm.pro
QMAKE_TARGET  = vegaihm
DESTDIR       = 
TARGET        = vegaihm

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: vegaihm.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile vegaihm.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile vegaihm.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/vegaihm1.0.0 || $(MKDIR) .tmp/vegaihm1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/vegaihm1.0.0/ && $(COPY_FILE) --parents configuration.h controlLink.h debug.h liveEvents.h md5.h pannels.h parameters.h printer.h switch.h vega_ihm.h rude/config.h /usr/include/mysql/mysql.h /usr/include/mysql/mysql_version.h /usr/include/mysql/mysql_com.h /usr/include/mysql/mysql_time.h /usr/include/mysql/typelib.h /usr/include/mysql/my_alloc.h /usr/include/mysql/my_list.h .tmp/vegaihm1.0.0/ && $(COPY_FILE) --parents icons.qrc .tmp/vegaihm1.0.0/ && $(COPY_FILE) --parents configuration.cpp controlLink.cpp debug.cpp DeviceKeysConfig.cpp liveEvents.cpp main.cpp md5.c parameters.cpp printer.cpp switch.cpp vega_ihm.cpp vega_ui_authentication.cpp vega_ui_conferences.cpp vega_ui_controllink.cpp vega_ui_devices.cpp vega_ui_groups.cpp vega_ui_init.cpp vega_ui_liveevents.cpp vega_ui_searchdb.cpp vega_ui_system_status.cpp .tmp/vegaihm1.0.0/ && (cd `dirname .tmp/vegaihm1.0.0` && $(TAR) vegaihm1.0.0.tar vegaihm1.0.0 && $(COMPRESS) vegaihm1.0.0.tar) && $(MOVE) `dirname .tmp/vegaihm1.0.0`/vegaihm1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/vegaihm1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_liveEvents.cpp moc_parameters.cpp moc_vega_ihm.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_liveEvents.cpp moc_parameters.cpp moc_vega_ihm.cpp
moc_liveEvents.cpp: liveEvents.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) liveEvents.h -o moc_liveEvents.cpp

moc_parameters.cpp: parameters.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) parameters.h -o moc_parameters.cpp

moc_vega_ihm.cpp: switch.h \
		liveEvents.h \
		parameters.h \
		controlLink.h \
		pannels.h \
		vega_ihm.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) vega_ihm.h -o moc_vega_ihm.cpp

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		imgs/flag_green.gif \
		imgs/flag_white.gif \
		imgs/flag_red.gif
	/usr/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

configuration.o: configuration.cpp rude/config.h \
		switch.h \
		debug.h \
		configuration.h \
		controlLink.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configuration.o configuration.cpp

controlLink.o: controlLink.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o controlLink.o controlLink.cpp

debug.o: debug.cpp debug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o debug.o debug.cpp

DeviceKeysConfig.o: DeviceKeysConfig.cpp switch.h \
		debug.h \
		configuration.h \
		rude/config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DeviceKeysConfig.o DeviceKeysConfig.cpp

liveEvents.o: liveEvents.cpp liveEvents.h \
		debug.h \
		vega_ihm.h \
		switch.h \
		parameters.h \
		controlLink.h \
		pannels.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o liveEvents.o liveEvents.cpp

main.o: main.cpp rude/config.h \
		vega_ihm.h \
		switch.h \
		liveEvents.h \
		parameters.h \
		controlLink.h \
		pannels.h \
		debug.h \
		configuration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

md5.o: md5.c md5.h \
		rude/config.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o md5.o md5.c

parameters.o: parameters.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o parameters.o parameters.cpp

printer.o: printer.cpp debug.h \
		printer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o printer.o printer.cpp

switch.o: switch.cpp rude/config.h \
		switch.h \
		debug.h \
		configuration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o switch.o switch.cpp

vega_ihm.o: vega_ihm.cpp rude/config.h \
		vega_ihm.h \
		switch.h \
		liveEvents.h \
		parameters.h \
		controlLink.h \
		pannels.h \
		debug.h \
		configuration.h \
		printer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vega_ihm.o vega_ihm.cpp

vega_ui_authentication.o: vega_ui_authentication.cpp vega_ihm.h \
		switch.h \
		liveEvents.h \
		parameters.h \
		controlLink.h \
		pannels.h \
		debug.h \
		configuration.h \
		printer.h \
		rude/config.h \
		md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vega_ui_authentication.o vega_ui_authentication.cpp

vega_ui_conferences.o: vega_ui_conferences.cpp vega_ihm.h \
		switch.h \
		liveEvents.h \
		parameters.h \
		controlLink.h \
		pannels.h \
		debug.h \
		configuration.h \
		printer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vega_ui_conferences.o vega_ui_conferences.cpp

vega_ui_controllink.o: vega_ui_controllink.cpp vega_ihm.h \
		switch.h \
		liveEvents.h \
		parameters.h \
		controlLink.h \
		pannels.h \
		configuration.h \
		debug.h \
		rude/config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vega_ui_controllink.o vega_ui_controllink.cpp

vega_ui_devices.o: vega_ui_devices.cpp vega_ihm.h \
		switch.h \
		liveEvents.h \
		parameters.h \
		controlLink.h \
		pannels.h \
		debug.h \
		configuration.h \
		printer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vega_ui_devices.o vega_ui_devices.cpp

vega_ui_groups.o: vega_ui_groups.cpp vega_ihm.h \
		switch.h \
		liveEvents.h \
		parameters.h \
		controlLink.h \
		pannels.h \
		debug.h \
		configuration.h \
		printer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vega_ui_groups.o vega_ui_groups.cpp

vega_ui_init.o: vega_ui_init.cpp vega_ihm.h \
		switch.h \
		liveEvents.h \
		parameters.h \
		controlLink.h \
		pannels.h \
		debug.h \
		configuration.h \
		printer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vega_ui_init.o vega_ui_init.cpp

vega_ui_liveevents.o: vega_ui_liveevents.cpp vega_ihm.h \
		switch.h \
		liveEvents.h \
		parameters.h \
		controlLink.h \
		pannels.h \
		debug.h \
		configuration.h \
		printer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vega_ui_liveevents.o vega_ui_liveevents.cpp

vega_ui_searchdb.o: vega_ui_searchdb.cpp vega_ihm.h \
		switch.h \
		liveEvents.h \
		parameters.h \
		controlLink.h \
		pannels.h \
		debug.h \
		configuration.h \
		printer.h \
		/usr/include/mysql/mysql.h \
		/usr/include/mysql/mysql_version.h \
		/usr/include/mysql/mysql_com.h \
		/usr/include/mysql/mysql_time.h \
		/usr/include/mysql/typelib.h \
		/usr/include/mysql/my_alloc.h \
		/usr/include/mysql/my_list.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vega_ui_searchdb.o vega_ui_searchdb.cpp

vega_ui_system_status.o: vega_ui_system_status.cpp switch.h \
		vega_ihm.h \
		liveEvents.h \
		parameters.h \
		controlLink.h \
		pannels.h \
		configuration.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vega_ui_system_status.o vega_ui_system_status.cpp

moc_liveEvents.o: moc_liveEvents.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_liveEvents.o moc_liveEvents.cpp

moc_parameters.o: moc_parameters.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_parameters.o moc_parameters.cpp

moc_vega_ihm.o: moc_vega_ihm.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vega_ihm.o moc_vega_ihm.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

